### ISSUE TITLE
we but where the file

### ISSUE THREAD

**Issue by sofiane6700** [prince214/4-grid-menu-landing-page#1]
we but where the file

**Comment by prince214** [comment]
You mean repo files ??
follow the link if thats the case : https://github.com/prince214/4-grid-menu-landing-page

**Comment by sofiane6700** [comment]
where to put the file in the game

**Comment by prince214** [comment]
I dont understand your question. What game are you talking about ? You can just clone or download the repo and open index.html file it work.
